$ANSIBLE_VAULT;1.1;AES256
38303166323639653735393334303639653633313236333031623736646331373636393363343963
6237666438343264313263653964386536393138656366340a303366613566306464376636386638
37633436636434623431353336636263366631396630653164386265373564373032646234393533
6334353833373763340a616130346430343833303736313237393633396539313537646363313935
61323966616566393532356663323864316361376230306138383362313837336536353035376335
38393234303437303836346534623436356232623937323235343865376437343564613064643538
363163376636343634343930613337303064
