all:
  children:
    webservers:  # <-- Changed from 'redis' to 'webservers'
      hosts:
        dev-env:
          ansible_host: 185.39.206.129
          ansible_user: root
          ansible_ssh_public_key_file: "~/.ssh/photozai.pub"
